/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ecommerce

import org.hibernate.boot.registry.StandardServiceRegistryBuilder
import org.hibernate.cfg.Configuration
import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.Id

class App {
    val greeting: String
        get() {
            val config = Configuration()
            config.configure().addAnnotatedClass(Message::class.java)
            val serviceRegistry = StandardServiceRegistryBuilder()
                .applySettings(config.properties)
                .build()
            val sf = config.buildSessionFactory(serviceRegistry)
            var messages: MutableList<Message>
            sf.use {
                val s = sf.openSession()
                s.beginTransaction()
                val msg = Message(text = "before")
                s.persist(msg)
                s.transaction.commit()

                s.beginTransaction()
                val c = s.criteriaBuilder.createQuery(Message::class.java)
                c.from(Message::class.java)
                messages = s.createQuery(c).resultList
                s.transaction.commit()
            }
            return "Hello World! number of messages: '${messages.size}'"
        }
}

fun main() {
    println(App().greeting)
}

@Entity
class Message(
    @Id
    @GeneratedValue
    val id: Long? = null,
    var text: String,
)
